package com.contractdrift.domain;

public enum ChangeType {
    ENDPOINT_REMOVED,
    ENDPOINT_ADDED,
    PARAMETER_REMOVED,
    PARAMETER_BECAME_REQUIRED,
    PARAMETER_TYPE_CHANGED,
    REQUEST_PROPERTY_REMOVED,
    REQUEST_PROPERTY_BECAME_REQUIRED,
    REQUEST_PROPERTY_TYPE_CHANGED,
    RESPONSE_REMOVED,
    RESPONSE_PROPERTY_REMOVED,
    RESPONSE_PROPERTY_TYPE_CHANGED
}
